# fly.toml file generated for wmm-selenium on 2022-10-03T23:39:03+02:00

app = "wmm-selenium"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[build]
  image = "selenium/standalone-chrome"
